version: '3'
services:

    wordpress:
        build: './wordpress'
        ports: 
            - "8080:80"
        environment:
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: mysql_user
            WORDPRESS_DB_PASSWORD: mysql_pw
        depends_on: 
            - mysql
        volumes: 
        - ./src:/var/www/html
  
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: root_pw
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_pw
        volumes: 
            - mysql_data:/var/lib/mysql
  
volumes:
    mysql_data:
